language: python
matrix:
  include:
  - python: 3.5-dev
    env: TOXENV=py35-release,coveralls
  - python: 3.5-dev
    env: TOXENV=py35-devel,coveralls
  - python: 3.4
    env: TOXENV=py34-release,coveralls
  - python: 3.4
    env: TOXENV=py34-devel,coveralls
  - python: 3.3
    env: TOXENV=py33-release,coveralls
  - python: 3.3
    env: TOXENV=py33-devel,coveralls
  - python: 2.7
    env: TOXENV=py27-release,coveralls
  - python: 2.7
    env: TOXENV=py27-devel,coveralls
  - python: 2.6
    env: TOXENV=py26-release,coveralls
  - python: 2.6
    env: TOXENV=py26-devel,coveralls
install: pip install tox
script: tox
